version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES}
      - HTTPPROXY=${HTTPPROXY}
    ports:
      - 8112:8112 # Deluge
    volumes:
      - ./config/gluetun/:/gluetun/

  deluge:
    image: linuxserver/deluge:latest
    container_name: deluge
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./config/deluge/:/config/
      - ./data/downloads/:/data/downloads/

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 9696:9696
    volumes:
      - ./config/prowlarr/:/config/

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
    - 7878:7878
    volumes:
      - ./config/radarr/:/config/
      - ./data/:/data/

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8989:8989
    volumes:
      - ./config/sonarr/:/config/
      - ./data/:/data/

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}  
    ports:
      - 6767:6767
    volumes:
      - ./config/bazarr/:/config/
      - ./data/media/movies/:/movies/
      - ./data/media/tv/:/tv/

  plex:
    image: linuxserver/plex:latest
    container_name: plex
    network_mode: host
    devices:
      - "/dev/dri:/dev/dri"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./config/plex/:/config/
      - ./data/media/tv/:/tv/
      - ./data/media/movies/:/movies/
      - ./data/media/music/:/music/